### ISSUE TITLE
ExtensionServer cluster certificates need to be propagated to all joiners

### ISSUE THREAD

**Issue by masnax** [canonical/microcluster#143]

**Comment by roosterfish** [comment]
Another question for this issue is how do we handle certificates that have expired? At some point you might need to replace the certificate on all cluster members.
So should this be something covered by MicroCluster or something an administrator has to perform outside of MicroCluster?

If it's the latter I am wondering if the initial exchange of the certificate should be done by MicroCluster if it's just a one time thing until the certs expire.

**Comment by masnax** [comment]
Closed by https://github.com/canonical/microcluster/pull/174
