### ISSUE TITLE
Reserve all of the top level API paths

### ISSUE THREAD

**Issue by roosterfish** [canonical/microcluster#227]
See https://github.com/canonical/microcluster/pull/224#issuecomment-2270107231

To prevent future collisions with endpoint paths introduced by downstream projects that might collide with new endpoints we add ourselves to microcluster, the following top level paths should be reserved when additional endpoints get added to the core API:

* `/core/control`
* `/core/internal`
* `/core/1.0`

**Comment by MggMuggins** [comment]
Is there any particular reason not to simply reserve the entire `/core` namespace? Even if we don't use any other endpoints under `/core` I think preventing users from using `/core` makes sense from an organization standpoint.

Ty @masnax for the suggestion.

**Comment by MggMuggins** [comment]
Any reason not to exclude the `/unix` endpoints as well? There's certainly an opportunity for collisions. That said, a MicroCluster consumer doing something like `/1.0/unix` with `ServeUnix: true` could/would be confusing to a consumer of their control socket if that consumer were also hitting, say, `/unix/tokens`.

**Comment by masnax** [comment]
> Any reason not to exclude the `/unix` endpoints as well? There's certainly an opportunity for collisions. That said, a MicroCluster consumer doing something like `/1.0/unix` with `ServeUnix: true` could/would be confusing to a consumer of their control socket if that consumer were also hitting, say, `/unix/tokens`.

`/core/control` is the unix endpoint, so it should be covered already by restricting `/core`. Microcluster doesn't have a `/unix` endpoint?

That would mean it's still possible to create a `/1.0/core/control` endpoint with `ServeUnix: true` on the core server or any extension servers, but I think that's fine, it shouldn't be on us to police how confusing downstream projects' API paths are. I think it's sufficient to simply say anything prefixed with `/core` means "microcluster", so that shouldn't be allowed on any extension server either.

**Comment by MggMuggins** [comment]
For some reason I was thinking [these](https://github.com/canonical/microcluster/blob/v3/internal/endpoints/endpoint.go#L27) were used as a `Resource.PathPrefix`. I stand corrected.

Agree that we can't be responsible for downstream choices; we should make it easy to move in the right direction.
